# Generated by Django 4.2.7 on 2023-12-02 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trick_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('not_landed', 'Not Landed'), ('landed_sketchy', 'Landed Sketchy'), ('landed_clean', 'Landed Clean'), ('on_lock', 'On Lock')], max_length=20)),
                ('trick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trick_tracker.trick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Placeholder',
        ),
    ]
