# Generated by Django 4.2.7 on 2024-03-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trick_tracker', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
